### ISSUE TITLE
Command raised an exception: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by mauvehed** [savioxavier/repo-finder-bot#16]
So far this has only happened with my local instance of repo-finder-bot, specifically the one running from the Dockerfile I submitted in #15. Has anyone else seen this? You search for a repo and it throws an error from discord.py, you run the exact same search again and it succeeds. I've seen this a couple times so far but I've failed to catch the debug output from the container.

I'll try and post that here next time I see it.

![image](https://user-images.githubusercontent.com/141381/140598744-f6d7424e-0bef-43b5-bd4c-351bf3f743e7.png)

**Comment by V3ntus** [comment]
It might be GitHub API not returning a proper response. If you can get a snapshot of the debug log when the error occurs, that might give some info. Although, because of how the log handler is programmed, I'm not sure if some information will be missing or not. That's on a TODO

**Comment by mauvehed** [comment]
Yeah, I figured if anything this is a good thing to note the need for better exception handling from discord.py

**Comment by V3ntus** [comment]
> Yeah, I figured if anything this is a good thing to note the need for better exception handling from discord.py

Agreed. Probably some sort of retry function implementation? Either retry the HTTP query, or save some traffic and just reroll a random index value, *that is* assuming we got a response of usable results in the first place. I'll have to test it out

Thanks for raising this issue 👍

**Comment by mauvehed** [comment]
I think I figured it out. Looks like my IPS was actively blocking connections to github.com at various times.

**Comment by V3ntus** [comment]
> I think I figured it out. Looks like my IPS was actively blocking connections to github.com at various times.

Ah ok, glad you got it figured out!

I think we'd still like to implement some sort of retry feature to mitigate situations like that
